// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnjucfzledlwtzjllkqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduanVjZnpsZWRsd3R6amxsa3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NjgyNzUsImV4cCI6MjA2ODE0NDI3NX0.9huLQ9EDT-QO5NiBd5nouxL26mupDdWMY-XQRe3tSgc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});